language: php

dist: trusty

sudo: false

services:
    - docker

addons:
    apt:
        packages:
            - docker-ce

cache:
    directories:
        - $HOME/.composer/cache/files

branches:
    only:
        - master

matrix:
    fast_finish: true
    include:
        - php: '7.2'
          env: TARGET=test
        - php: '7.2'
          env: TARGET=check

install:
    - make install

script: make $TARGET
